export const PARTS = [
    {
      id: "a1f0c9d7-81b1-4b5d-bb0c-2c29af57c0fa",
      name: "Full-suspension",
      part_type: "frame_type",
      description: "A frame type ideal for off-road and mountain biking.",
      price: 130,
    },
    {
      id: "c5b2e7f1-092b-43b9-b6f7-d6a0f092e44a",
      name: "Diamond",
      part_type: "frame_type",
      description: "A classic frame type offering excellent stability.",
      price: 100,
    },
    {
      id: "73d3be42-84c8-4d41-86b9-42f3e9c0132b",
      name: "Step-through",
      part_type: "frame_type",
      description: "A frame type designed for easy mounting and dismounting.",
      price: 110,
    },
    {
      id: "b347d939-d8c4-4c1c-8f8e-5cfc8d3c7c5b",
      name: "Matte",
      part_type: "frame_finish",
      description: "A non-reflective, elegant finish for the bike frame.",
      price: 30,
    },
    {
      id: "7f2e72f9-f9cb-4c3b-87bb-7f2c32d3f98b",
      name: "Shiny",
      part_type: "frame_finish",
      description: "A reflective, polished finish for a premium look.",
      price: 50,
    },
    {
      id: "d9c9e7a4-f4dc-4fd8-bf23-6a8e56e9c3f0",
      name: "Road wheels",
      part_type: "wheel",
      description: "Wheels optimized for smooth and fast road cycling.",
      price: 80,
    },
    {
      id: "fc4d5e6c-71c2-4d87-b33e-d5a9b91a11d7",
      name: "Mountain wheels",
      part_type: "wheel",
      description:
        "Durable wheels designed for rough terrain and mountain biking.",
      price: 90,
    },
    {
      id: "49bcb632-36f8-4926-8c8e-923a63a6f29d",
      name: "Fat bike wheels",
      part_type: "wheel",
      description:
        "Extra-wide wheels for enhanced stability on sand, snow, or loose terrain.",
      price: 120,
    },
    {
      id: "ac9e4821-7e7c-44eb-946b-4bd2e693c92b",
      name: "Red",
      part_type: "rim_color",
      color: "#eb4034",
      description: "A vibrant red rim color for a bold look.",
      price: 15,
    },
    {
      id: "d2e4f76b-9087-4cfd-80f6-917f6e69b2cf",
      name: "Black",
      part_type: "rim_color",
      color: "#04040f",
      description: "A sleek black rim color for a classic appearance.",
      price: 10,
    },
    {
      id: "3cfd382d-48c2-4ab5-a6d7-abcfe6b49392",
      name: "Blue",
      part_type: "rim_color",
      color: "#0d12a1",
      description: "A cool blue rim color for a distinct style.",
      price: 20,
      disabled: true,
    },
    {
      id: "72bc4f69-87ef-42f3-82b7-7e7f9c6c3b87",
      name: "Single-speed chain",
      part_type: "chain",
      description: "A chain optimized for single-speed bicycles.",
      price: 43,
    },
    {
      id: "c8f9e8d6-7c34-4d2c-91b6-bfc6d89c91c6",
      name: "8-speed chain",
      part_type: "chain",
      description: "A chain designed for multi-speed bikes with 8 gears.",
      price: 60,
    },
  ];
  